### ISSUE TITLE
Error creating main figure

### ISSUE THREAD

**Issue by jiazesun0622** [neuroelf/neuroelf-matlab#4]
When I finished installation and tried to started NeuroElf with neuroelf_gui, some error suggestion showed whether I installed in Windows or Mac.

>> neuroelf_gui
NeuroElf (17061221): figure... core config... UI config...Error using neuroelf_gui (line 579)
Error creating main figure: Unrecognized property Position for class AnnotationPane.

**Comment by igorkagan** [comment]
This **might** be related to MATLAB version - which one you are using?

**Comment by jiazesun0622** [comment]
Dear,

I am using Matlab2020a.

Jiaze

**Comment by igorkagan** [comment]
Try earlier MATLAB versions, 2014/2015 work for us.

**Comment by neuroelf** [comment]
I assume that I fixed this (at least on my MacBook, I can open NeuroElf with 2020b).

**Comment by alexsayal** [comment]
Hello @neuroelf ,

This problem still happens on Matlab R2020 in both Ubuntu 20.04 and Windows 10. Could you please let us know what you did to fix this?

Thank you in advance,

**Comment by neuroelf** [comment]
Dear Alexandre,

Sorry for the delay... In case you have some time (maybe next week), could
we plan for a shared-screen (zoom or some such) video call where you
demonstrate the issue. Since I cannot replicate it (with the updated code
base, did you pull the latest changes?), I don't know how to fix it...

/jochen

**Comment by alexsayal** [comment]
Hello @neuroelf ,

After pulling the last changes from the repository all is okay. I guess I still had the .zip version you can get from the website in these computers.

Thank you!

**Comment by neuroelf** [comment]
Hello Alexandre,

I'm glad it's working now! :) Thanks for letting me know!!

Best,
/jochen
